services:
  mysql:
    image: mysql:8.4 # 이미지 이름 : 버전
    container_name: vote-mysql # docker ps에서 보이는 컨테이너 이름
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306" # 호스트포트 : 컨테이너포트
    volumes:
      - mysql-data:/var/lib/mysql # 볼륨명 : 컨테이너 내 데이터 경로 MySQL은 /var/lib/mysql에 데이터를 저장
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 추가옵션
                                                                                  # 문자셋 설정

  redis:
    image: redis:8.0
    container_name: vote-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes # AOF 영속성 활성화 모든 쓰기 명령을 디스크에 기록

  prometheus: # 이 이름이 Docker 내부 도메인이 됨
    image: prom/prometheus:latest
    container_name: vote-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway" # 컨테이너에서 호스트 앱(8080) 접근용

  grafana:
    image: grafana/grafana:11.3.0
    container_name: vote-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      # 볼륨 마운트를 읽는 법: 호스트경로:컨테이너경로
      # /etc/grafana/provisioning -> Grafana 시작 시 자동으로 스캔하는 경로
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  mysql-data:
  redis-data:
  prometheus-data:
  grafana-data: