spring:
  datasource:
    url: jdbc:mysql://localhost:3307/${DB_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # 실행마다 테이블 새로 생성 초기 단계이므로 create로 지정
    show-sql: true # 실행 SQL 콘솔 출력
    properties:
      hibernate:
        format_sql: true # show-sql로 출력되는 SQL을 들여쓰기 정렬
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

server:
  tomcat:
    mbeanregistry:
      # 해당 설정을 켜야 Tomcat 내부 MBean에서 스레드 풀 정보를 읽어올 수 있다.
      enabled: true # tomcat_threads_* 메트릭 노출 활성화 (기본값 false)